-- V2-6B.3 Supabase/Postgres schema draft for historical market collection.
-- This file is a draft only and is not applied by this repository.
-- Do not add secrets, project URLs, service role keys, or source API credentials here.

create extension if not exists pgcrypto;

create table if not exists collector_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  started_at timestamptz not null,
  finished_at timestamptz,
  status text not null,
  item_count integer not null default 0,
  transaction_candidate_count integer not null default 0,
  snapshot_candidate_count integer not null default 0,
  inserted_transaction_count integer not null default 0,
  inserted_snapshot_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  constraint collector_runs_status_check
    check (status in ('running', 'succeeded', 'partial', 'failed'))
);

create index if not exists collector_runs_source_started_at_idx
  on collector_runs (source, started_at desc);

create table if not exists items (
  source text not null,
  item_id text not null,
  name text not null,
  group_name text not null,
  category text not null,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (source, item_id)
);

create index if not exists items_source_category_idx
  on items (source, category);

create table if not exists market_transactions (
  source text not null,
  item_id text not null,
  transaction_id text not null,
  transaction_time timestamptz not null,
  quantity numeric not null,
  total_value numeric not null,
  unit_value numeric not null,
  currency text not null,
  seller_id text not null,
  seller_name text not null,
  buyer_id text not null,
  buyer_name text not null,
  raw_hash text not null,
  raw jsonb not null default '{}'::jsonb,
  collector_run_id uuid references collector_runs(id),
  created_at timestamptz not null default now(),
  primary key (source, item_id, transaction_id),
  constraint market_transactions_item_fk
    foreign key (source, item_id) references items(source, item_id),
  constraint market_transactions_quantity_check
    check (quantity > 0),
  constraint market_transactions_total_value_check
    check (total_value >= 0),
  constraint market_transactions_unit_value_check
    check (unit_value >= 0)
);

create unique index if not exists market_transactions_raw_hash_key
  on market_transactions (raw_hash);

create index if not exists market_transactions_source_time_idx
  on market_transactions (source, transaction_time desc);

create index if not exists market_transactions_item_time_idx
  on market_transactions (source, item_id, transaction_time desc);

create index if not exists market_transactions_seller_time_idx
  on market_transactions (source, seller_id, transaction_time desc);

create index if not exists market_transactions_buyer_time_idx
  on market_transactions (source, buyer_id, transaction_time desc);

create table if not exists price_snapshots (
  source text not null,
  item_id text not null,
  snapshot_time timestamptz not null,
  trade_count integer not null default 0,
  total_quantity numeric not null default 0,
  total_value numeric not null default 0,
  min_unit_value numeric,
  max_unit_value numeric,
  avg_unit_value numeric not null default 0,
  last_unit_value numeric,
  currency text not null,
  collector_run_id uuid references collector_runs(id),
  created_at timestamptz not null default now(),
  primary key (source, item_id, snapshot_time),
  constraint price_snapshots_item_fk
    foreign key (source, item_id) references items(source, item_id),
  constraint price_snapshots_trade_count_check
    check (trade_count >= 0),
  constraint price_snapshots_total_quantity_check
    check (total_quantity >= 0),
  constraint price_snapshots_total_value_check
    check (total_value >= 0),
  constraint price_snapshots_avg_unit_value_check
    check (avg_unit_value >= 0)
);

create index if not exists price_snapshots_source_time_idx
  on price_snapshots (source, snapshot_time desc);

create index if not exists price_snapshots_item_time_idx
  on price_snapshots (source, item_id, snapshot_time desc);

-- ELF skin gallery community stats.
-- Public clients use only sync_skin_gallery_state(); they do not write tables directly.
-- visitor_id is an anonymous browser UUID generated by the frontend and stored in localStorage.

create table if not exists skin_gallery_visitors (
  visitor_id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_count integer not null default 1,
  constraint skin_gallery_visitors_visit_count_check
    check (visit_count > 0)
);

create table if not exists skin_gallery_wishes (
  visitor_id uuid not null references skin_gallery_visitors(visitor_id) on delete cascade,
  skin_id text not null,
  selected_at timestamptz not null default now(),
  primary key (visitor_id, skin_id),
  constraint skin_gallery_wishes_skin_id_check
    check (length(trim(skin_id)) > 0)
);

create index if not exists skin_gallery_wishes_skin_id_idx
  on skin_gallery_wishes (skin_id);

alter table skin_gallery_visitors enable row level security;
alter table skin_gallery_wishes enable row level security;

revoke all on skin_gallery_visitors from anon, authenticated;
revoke all on skin_gallery_wishes from anon, authenticated;

create or replace function get_skin_gallery_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'visitorCount', (select count(*)::integer from skin_gallery_visitors),
    'wishlistLeaders', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'skinId', ranked.skin_id,
            'wishCount', ranked.wish_count
          )
          order by ranked.wish_count desc, ranked.skin_id
        )
        from (
          select
            skin_id,
            count(*)::integer as wish_count
          from skin_gallery_wishes
          group by skin_id
          order by count(*) desc, skin_id
          limit 5
        ) ranked
      ),
      '[]'::jsonb
    )
  );
$$;

create or replace function sync_skin_gallery_state(
  p_visitor_id uuid,
  p_skin_ids text[] default '{}'::text[]
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  insert into skin_gallery_visitors as visitors (
    visitor_id,
    first_seen_at,
    last_seen_at,
    visit_count
  )
  values (
    p_visitor_id,
    now(),
    now(),
    1
  )
  on conflict (visitor_id) do update
    set
      last_seen_at = excluded.last_seen_at,
      visit_count = visitors.visit_count + 1;

  delete from skin_gallery_wishes
  where visitor_id = p_visitor_id
    and skin_id not in (
      select normalized.skin_id
      from (
        select distinct trim(skin_id) as skin_id
        from unnest(coalesce(p_skin_ids, '{}'::text[])) as skin_id
        where length(trim(skin_id)) > 0
        order by 1
        limit 3
      ) normalized
    );

  insert into skin_gallery_wishes (
    visitor_id,
    skin_id,
    selected_at
  )
  select
    p_visitor_id,
    normalized.skin_id,
    now()
  from (
    select distinct trim(skin_id) as skin_id
    from unnest(coalesce(p_skin_ids, '{}'::text[])) as skin_id
    where length(trim(skin_id)) > 0
    order by 1
    limit 3
  ) normalized
  on conflict (visitor_id, skin_id) do nothing;

  return get_skin_gallery_stats();
end;
$$;

grant execute on function get_skin_gallery_stats() to anon, authenticated;
grant execute on function sync_skin_gallery_state(uuid, text[]) to anon, authenticated;
